# For docker compose all services are run in the same network
version: '3.8'
services:
  # backend:
    
  # frontend:
    
  mongodb:
    image: 'mongo'
    volumes:
      - data:/data/db
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=admin
    #   - MONGO_INITDB_ROOT_PASSWORD=admin
    env_file:
      - ./env/mongo.env
volumes:
  data: